[E 2018-12-25 10:28:37 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 12, in post
        status_code = self.request.body()
    TypeError: 'bytes' object is not callable
[E 2018-12-25 10:29:30 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 12, in post
        status_code = json.loads(self.request.body())
    TypeError: 'bytes' object is not callable
[E 2018-12-25 10:29:56 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 12, in post
        def post(self):
    TypeError: 'bytes' object is not callable
[E 2018-12-25 10:30:13 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 12, in post
        def post(self):
    TypeError: 'bytes' object is not callable
[E 2018-12-25 10:30:44 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 12, in post
        def post(self):
    TypeError: 'bytes' object is not callable
[E 2018-12-25 10:30:55 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 12, in post
        def post(self):
    TypeError: 'bytes' object is not callable
[E 2018-12-25 10:31:16 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 13, in post
        status_code = json.loads(self.request.body())
    TypeError: 'bytes' object is not callable
[E 2018-12-25 10:40:45 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 14, in post
        status_code = data['code']
    TypeError: byte indices must be integers or slices, not str
[E 2018-12-25 10:41:06 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 15, in post
        self.write(status_code)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 744, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
[E 2018-12-25 10:41:28 log_exception:1670] Uncaught exception POST /getinfo (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='POST', uri='/getinfo', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\getinfohandler.py", line 16, in post
        self.write(status_code)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 744, in write
        raise TypeError(message)
    TypeError: write() only accepts bytes, unicode, and dict objects
[E 2018-12-25 17:41:48 log_exception:1670] Uncaught exception GET /getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030 (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='GET', uri='/getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1592, in _execute
        result = yield result
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1221, in handle_yield
        self.future = convert_yielded(yielded)
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\functools.py", line 824, in wrapper
        return dispatch(args[0].__class__)(*args, **kw)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1357, in convert_yielded
        return multi(yielded)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 773, in multi
        return multi_future(children, quiet_exceptions=quiet_exceptions)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 868, in multi_future
        children = list(map(convert_yielded, children))
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\functools.py", line 824, in wrapper
        return dispatch(args[0].__class__)(*args, **kw)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1363, in convert_yielded
        raise BadYieldError("yielded unknown object %r" % (yielded,))
    tornado.gen.BadYieldError: yielded unknown object '\r<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\r\r<html xmlns="http://www.w3.org/1999/xhtml">\r<head>\r<meta charset="utf-8">\r<meta http-equiv="Cache-Control" content="no-cache"/>\r<title>500-Õ¨≤Ω÷˙ ÷</title>\r<style type="text/css">\rhtml,body,div,h1,p,span.a{ margin: 0; padding: 0;}\rhtml{ height: 100%; width: 100%;}\rbody{ background: #315379 url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-bg-r.png) repeat-x; height: 100%; width: 100%;font: normal 12px/1.5 Œ¢»Ì—≈∫⁄;}\r.wrapper{ background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-bg.jpg) no-repeat top center; text-align: center; height: 100%; width: 100%; color: #fff;}\r.wrapper h1{ font-size: 60px; font-weight: normal; padding-top: 15px;}\r.sub-h{ font-size: 24px;}\r.sub-h-e{ font-weight: bold;}\r.guide-tit{ margin-top: 130px; color: #223a54; font-size: 18px; }\r.btn-bar{ padding-top: 30px; text-align: left; width: 830px; margin: auto; overflow: hidden; font-size: 18px; color: #57799f;}\r\t.btn-bar-innerbox{ width: 870px;}\r\t.btn{ float: left; background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn.png) no-repeat; height: 64px; width: 214px; padding: 6px 15px 0; margin: 3px 43px 3px 3px;\r\t\t_filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn.png\'); _background-image: none;\r\t}\r\t.hover{background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn-hover.png) no-repeat; margin: 0 40px 0px 0px; padding: 9px 18px 0; height: 70px;\r\t\t_filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn-hover.png\'); _background-image: none; \r\t}\r.btn-bar .h{ display: block; margin-bottom: 3px; zoom:1;}\ra{ color: #57799f;}\ra:hover{ color: #fff;}\r</style>\r</head>\r\r<body>\r<div class="wrapper">\r\t<h1>500</h1>\r\t<p class="sub-h">œ‡–≈Œ“√«£¨’‚÷ª «“ª∏ˆŒ¥÷™–°“‚Õ‚°£÷ª“™µÿ«Ú≤ªªŸ√£¨’‚∆¨‘∆Ω´”Îƒ˙Õ¨‘⁄°£</p>\r\t<p class="sub-h-e">The server encountered an internal error or misconfiguration and was unable to complete your request.</p>\r\t<p class="guide-tit">∏Ûœ¬ø…“‘≥¢ ‘Ω¯»Î“‘œ¬”–◊È÷Øµƒøø∆◊‘∆</p>\r\t<div class="btn-bar"><div class="btn-bar-innerbox">\r\t\t<span class="btn" id="btn1">\r\t\t\t<span class="h">œ¬‘ÿ ÷ª˙∂À</span>\r\t\t\t<a href="http://pim.qq.com/down.jsp">QQÕ¨≤Ω÷˙ ÷</a>ªÚ<a href="http://txl.qq.com/main/download.jsp">QQÕ®—∂¬º</a>\r\t\t</span>\r\t\t<span class="btn" id="btn2">\r\t\t\t<span class="h">π‹¿Ì</span>\r\t\t\t<a href="http://ic.qq.com">∏Ûœ¬±∏∑›‘⁄‘∆∂Àµƒ◊ ¡œ</a>\r\t\t</span>\r\t\t<span class="btn" id="btn3">\r\t\t\t<span class="h">œ¬‘ÿ</span>\r\t\t\t<a href="http://tx.myapp.com/software/">∆‰À˚Ã⁄—∂ ÷ª˙”¶”√</a>\r\t\t</span>\r\t</div></div>\r</div>\r<script type="text/javascript">\r(function(){\r\tfunction hover(){\r\t\tthis.className = this.className + \' hover\';\r\t}\r\t\r\tfunction leave(){\r\t\tthis.className = this.className.replace(\' hover\',\'\');\r\t}\r\t\r\tfunction $(id){\r\t\treturn document.getElementById(id);\r\t}\r\t\r\tvar btns = [\'btn1\',\'btn2\',\'btn3\'];\r\tfor(var i = 0; i < 3; i++){\r\t\t$(btns[i]).onmouseover = hover;\r\t\t$(btns[i]).onmouseout = leave;\r\t}\r})();\r</script>\r</body>\r</html>\r'
[E 2018-12-25 17:42:28 log_exception:1670] Uncaught exception GET /getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030 (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='GET', uri='/getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1592, in _execute
        result = yield result
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1221, in handle_yield
        self.future = convert_yielded(yielded)
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\functools.py", line 824, in wrapper
        return dispatch(args[0].__class__)(*args, **kw)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1357, in convert_yielded
        return multi(yielded)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 773, in multi
        return multi_future(children, quiet_exceptions=quiet_exceptions)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 868, in multi_future
        children = list(map(convert_yielded, children))
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\functools.py", line 824, in wrapper
        return dispatch(args[0].__class__)(*args, **kw)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1363, in convert_yielded
        raise BadYieldError("yielded unknown object %r" % (yielded,))
    tornado.gen.BadYieldError: yielded unknown object '\r<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\r\r<html xmlns="http://www.w3.org/1999/xhtml">\r<head>\r<meta charset="utf-8">\r<meta http-equiv="Cache-Control" content="no-cache"/>\r<title>500-Õ¨≤Ω÷˙ ÷</title>\r<style type="text/css">\rhtml,body,div,h1,p,span.a{ margin: 0; padding: 0;}\rhtml{ height: 100%; width: 100%;}\rbody{ background: #315379 url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-bg-r.png) repeat-x; height: 100%; width: 100%;font: normal 12px/1.5 Œ¢»Ì—≈∫⁄;}\r.wrapper{ background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-bg.jpg) no-repeat top center; text-align: center; height: 100%; width: 100%; color: #fff;}\r.wrapper h1{ font-size: 60px; font-weight: normal; padding-top: 15px;}\r.sub-h{ font-size: 24px;}\r.sub-h-e{ font-weight: bold;}\r.guide-tit{ margin-top: 130px; color: #223a54; font-size: 18px; }\r.btn-bar{ padding-top: 30px; text-align: left; width: 830px; margin: auto; overflow: hidden; font-size: 18px; color: #57799f;}\r\t.btn-bar-innerbox{ width: 870px;}\r\t.btn{ float: left; background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn.png) no-repeat; height: 64px; width: 214px; padding: 6px 15px 0; margin: 3px 43px 3px 3px;\r\t\t_filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn.png\'); _background-image: none;\r\t}\r\t.hover{background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn-hover.png) no-repeat; margin: 0 40px 0px 0px; padding: 9px 18px 0; height: 70px;\r\t\t_filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn-hover.png\'); _background-image: none; \r\t}\r.btn-bar .h{ display: block; margin-bottom: 3px; zoom:1;}\ra{ color: #57799f;}\ra:hover{ color: #fff;}\r</style>\r</head>\r\r<body>\r<div class="wrapper">\r\t<h1>500</h1>\r\t<p class="sub-h">œ‡–≈Œ“√«£¨’‚÷ª «“ª∏ˆŒ¥÷™–°“‚Õ‚°£÷ª“™µÿ«Ú≤ªªŸ√£¨’‚∆¨‘∆Ω´”Îƒ˙Õ¨‘⁄°£</p>\r\t<p class="sub-h-e">The server encountered an internal error or misconfiguration and was unable to complete your request.</p>\r\t<p class="guide-tit">∏Ûœ¬ø…“‘≥¢ ‘Ω¯»Î“‘œ¬”–◊È÷Øµƒøø∆◊‘∆</p>\r\t<div class="btn-bar"><div class="btn-bar-innerbox">\r\t\t<span class="btn" id="btn1">\r\t\t\t<span class="h">œ¬‘ÿ ÷ª˙∂À</span>\r\t\t\t<a href="http://pim.qq.com/down.jsp">QQÕ¨≤Ω÷˙ ÷</a>ªÚ<a href="http://txl.qq.com/main/download.jsp">QQÕ®—∂¬º</a>\r\t\t</span>\r\t\t<span class="btn" id="btn2">\r\t\t\t<span class="h">π‹¿Ì</span>\r\t\t\t<a href="http://ic.qq.com">∏Ûœ¬±∏∑›‘⁄‘∆∂Àµƒ◊ ¡œ</a>\r\t\t</span>\r\t\t<span class="btn" id="btn3">\r\t\t\t<span class="h">œ¬‘ÿ</span>\r\t\t\t<a href="http://tx.myapp.com/software/">∆‰À˚Ã⁄—∂ ÷ª˙”¶”√</a>\r\t\t</span>\r\t</div></div>\r</div>\r<script type="text/javascript">\r(function(){\r\tfunction hover(){\r\t\tthis.className = this.className + \' hover\';\r\t}\r\t\r\tfunction leave(){\r\t\tthis.className = this.className.replace(\' hover\',\'\');\r\t}\r\t\r\tfunction $(id){\r\t\treturn document.getElementById(id);\r\t}\r\t\r\tvar btns = [\'btn1\',\'btn2\',\'btn3\'];\r\tfor(var i = 0; i < 3; i++){\r\t\t$(btns[i]).onmouseover = hover;\r\t\t$(btns[i]).onmouseout = leave;\r\t}\r})();\r</script>\r</body>\r</html>\r'
[E 2018-12-25 17:43:02 log_exception:1670] Uncaught exception GET /getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030 (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='GET', uri='/getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1592, in _execute
        result = yield result
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1221, in handle_yield
        self.future = convert_yielded(yielded)
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\functools.py", line 824, in wrapper
        return dispatch(args[0].__class__)(*args, **kw)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1357, in convert_yielded
        return multi(yielded)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 773, in multi
        return multi_future(children, quiet_exceptions=quiet_exceptions)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 868, in multi_future
        children = list(map(convert_yielded, children))
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\functools.py", line 824, in wrapper
        return dispatch(args[0].__class__)(*args, **kw)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1363, in convert_yielded
        raise BadYieldError("yielded unknown object %r" % (yielded,))
    tornado.gen.BadYieldError: yielded unknown object '1'
[E 2018-12-25 17:44:11 log_exception:1670] Uncaught exception GET /getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030 (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='GET', uri='/getinfo?mobile=15225356560&verify=336948&user_id=346&t_user_agent=017D9201CFB1E5927E5E051443844141&SESSION_JSESSIONID=6059834c-1ca1-4f3c-9748-46d7d6b01c1c&csrf=5275127820459188030', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1592, in _execute
        result = yield result
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1221, in handle_yield
        self.future = convert_yielded(yielded)
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\functools.py", line 824, in wrapper
        return dispatch(args[0].__class__)(*args, **kw)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\gen.py", line 1363, in convert_yielded
        raise BadYieldError("yielded unknown object %r" % (yielded,))
    tornado.gen.BadYieldError: yielded unknown object '{"code": "\\r<!DOCTYPE html PUBLIC \\"-//W3C//DTD XHTML 1.0 Transitional//EN\\" \\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\\">\\r\\r\\r<html xmlns=\\"http://www.w3.org/1999/xhtml\\">\\r<head>\\r<meta charset=\\"utf-8\\">\\r<meta http-equiv=\\"Cache-Control\\" content=\\"no-cache\\"/>\\r<title>500-\\u540c\\u6b65\\u52a9\\u624b</title>\\r<style type=\\"text/css\\">\\rhtml,body,div,h1,p,span.a{ margin: 0; padding: 0;}\\rhtml{ height: 100%; width: 100%;}\\rbody{ background: #315379 url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-bg-r.png) repeat-x; height: 100%; width: 100%;font: normal 12px/1.5 \\u5fae\\u8f6f\\u96c5\\u9ed1;}\\r.wrapper{ background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-bg.jpg) no-repeat top center; text-align: center; height: 100%; width: 100%; color: #fff;}\\r.wrapper h1{ font-size: 60px; font-weight: normal; padding-top: 15px;}\\r.sub-h{ font-size: 24px;}\\r.sub-h-e{ font-weight: bold;}\\r.guide-tit{ margin-top: 130px; color: #223a54; font-size: 18px; }\\r.btn-bar{ padding-top: 30px; text-align: left; width: 830px; margin: auto; overflow: hidden; font-size: 18px; color: #57799f;}\\r\\t.btn-bar-innerbox{ width: 870px;}\\r\\t.btn{ float: left; background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn.png) no-repeat; height: 64px; width: 214px; padding: 6px 15px 0; margin: 3px 43px 3px 3px;\\r\\t\\t_filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn.png\'); _background-image: none;\\r\\t}\\r\\t.hover{background: url(http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn-hover.png) no-repeat; margin: 0 40px 0px 0px; padding: 9px 18px 0; height: 70px;\\r\\t\\t_filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=\'http://3gsoft.gtimg.com/msoft/sec/webss/web_pim/images/404-btn-hover.png\'); _background-image: none; \\r\\t}\\r.btn-bar .h{ display: block; margin-bottom: 3px; zoom:1;}\\ra{ color: #57799f;}\\ra:hover{ color: #fff;}\\r</style>\\r</head>\\r\\r<body>\\r<div class=\\"wrapper\\">\\r\\t<h1>500</h1>\\r\\t<p class=\\"sub-h\\">\\u76f8\\u4fe1\\u6211\\u4eec\\uff0c\\u8fd9\\u53ea\\u662f\\u4e00\\u4e2a\\u672a\\u77e5\\u5c0f\\u610f\\u5916\\u3002\\u53ea\\u8981\\u5730\\u7403\\u4e0d\\u6bc1\\u706d\\uff0c\\u8fd9\\u7247\\u4e91\\u5c06\\u4e0e\\u60a8\\u540c\\u5728\\u3002</p>\\r\\t<p class=\\"sub-h-e\\">The server encountered an internal error or misconfiguration and was unable to complete your request.</p>\\r\\t<p class=\\"guide-tit\\">\\u9601\\u4e0b\\u53ef\\u4ee5\\u5c1d\\u8bd5\\u8fdb\\u5165\\u4ee5\\u4e0b\\u6709\\u7ec4\\u7ec7\\u7684\\u9760\\u8c31\\u4e91</p>\\r\\t<div class=\\"btn-bar\\"><div class=\\"btn-bar-innerbox\\">\\r\\t\\t<span class=\\"btn\\" id=\\"btn1\\">\\r\\t\\t\\t<span class=\\"h\\">\\u4e0b\\u8f7d\\u624b\\u673a\\u7aef</span>\\r\\t\\t\\t<a href=\\"http://pim.qq.com/down.jsp\\">QQ\\u540c\\u6b65\\u52a9\\u624b</a>\\u6216<a href=\\"http://txl.qq.com/main/download.jsp\\">QQ\\u901a\\u8baf\\u5f55</a>\\r\\t\\t</span>\\r\\t\\t<span class=\\"btn\\" id=\\"btn2\\">\\r\\t\\t\\t<span class=\\"h\\">\\u7ba1\\u7406</span>\\r\\t\\t\\t<a href=\\"http://ic.qq.com\\">\\u9601\\u4e0b\\u5907\\u4efd\\u5728\\u4e91\\u7aef\\u7684\\u8d44\\u6599</a>\\r\\t\\t</span>\\r\\t\\t<span class=\\"btn\\" id=\\"btn3\\">\\r\\t\\t\\t<span class=\\"h\\">\\u4e0b\\u8f7d</span>\\r\\t\\t\\t<a href=\\"http://tx.myapp.com/software/\\">\\u5176\\u4ed6\\u817e\\u8baf\\u624b\\u673a\\u5e94\\u7528</a>\\r\\t\\t</span>\\r\\t</div></div>\\r</div>\\r<script type=\\"text/javascript\\">\\r(function(){\\r\\tfunction hover(){\\r\\t\\tthis.className = this.className + \' hover\';\\r\\t}\\r\\t\\r\\tfunction leave(){\\r\\t\\tthis.className = this.className.replace(\' hover\',\'\');\\r\\t}\\r\\t\\r\\tfunction $(id){\\r\\t\\treturn document.getElementById(id);\\r\\t}\\r\\t\\r\\tvar btns = [\'btn1\',\'btn2\',\'btn3\'];\\r\\tfor(var i = 0; i < 3; i++){\\r\\t\\t$(btns[i]).onmouseover = hover;\\r\\t\\t$(btns[i]).onmouseout = leave;\\r\\t}\\r})();\\r</script>\\r</body>\\r</html>\\r"}'
[E 2018-12-26 11:58:49 log_exception:1670] Uncaught exception GET /qrcode (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='GET', uri='/qrcode', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\tb\qrcodehandler.py", line 17, in get
        img = requests.get(qrcode_url)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\requests\api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\requests\api.py", line 60, in request
        return session.request(method=method, url=url, **kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\requests\sessions.py", line 519, in request
        prep = self.prepare_request(req)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\requests\sessions.py", line 462, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\requests\models.py", line 313, in prepare
        self.prepare_url(url, params)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\requests\models.py", line 390, in prepare_url
        raise InvalidURL("Invalid URL %r: No host supplied" % url)
    requests.exceptions.InvalidURL: Invalid URL 'https:////img.alicdn.com/tfscom/TB1TPUsymzqK1RjSZFjwu2lCFXa.png': No host supplied
[E 2018-12-26 11:59:20 log_exception:1670] Uncaught exception GET /qrcode (192.168.1.10)
    HTTPServerRequest(protocol='http', host='192.168.1.10:8000', method='GET', uri='/qrcode', version='HTTP/1.1', remote_ip='192.168.1.10')
    Traceback (most recent call last):
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Jiqi008\PycharmProjects\untitled\python\handler\tb\qrcodehandler.py", line 20, in get
        img_json = tornado.escape.json_encode({'header': 'data:image/jpg;base64', 'body': data})
      File "C:\Users\Jiqi008\PycharmProjects\untitled\venv\lib\site-packages\tornado\escape.py", line 81, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "C:\Users\Jiqi008\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type bytes is not JSON serializable
